# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2307c0ddbea9d3d6b96c2363238c98a37e0c1007bac9a056b808d88bbc0051b5521f40373dad9687fda449e5983e518c24f374c4a21cba43a14d27f7b876099

test:
  secret_key_base: f08c0bb389d69208bcb3df621bda1b49bc214465764881a0e8610d792e29433efa016b8ecc4e0ce3ae5bca4f80fd503f484ab4e7fe1ad8933ae3be3e46d47fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
