# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c487d2c52197f43abb2e6b160b6fc1ac2915926666947950b5e4f5dff2304568fcffcc68db7c0e90a4e85e94d1a2978019479d228ed1a2683e93842647b3da42

test:
  secret_key_base: af3668530dfe3f3f97e448e4be627fe6846f8c6d5df6ddb883d9e1299b2777f470ad8177344ffc58458c5294ec920aab281a7da51977fa5a32339edd05d00082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
